require('options')
require('keys')

require('plugins.kimbox')
require('plugins.fzf')
-- require('plugins.gruvbox-material')
require('plugins.mason')
require('plugins.nvim-treesitter')
require('plugins.vim-better-whitespace')
require('plugins.vim-cmp')
require('plugins.vim-indent-guides')
require('plugins.vim-operator-replace')
require('plugins.lsp')
require('plugins.lspsaga')
require('plugins.gitsigns')
require('plugins.lualine')
